version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:4202"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Backend/EduPortalAPI
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - ASPNETCORE_URLS=http://+:8085
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=Learnova;User Id=sa;Password=Pass@1234;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1436:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@1234
      - MSSQL_PID=Express
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Pass@1234' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data:
    driver: local
  mssql_log:
    driver: local
