name: Deploy Angular App to S3

on:
  push:
    branches:
      - main  # Trigger deployment when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
          source_dir: dist/learnova/browser   # ✅ Correct path to your static files
        env:
          AWS_S3_BUCKET: e-learn-fe           # ✅ Your S3 bucket name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
