name: Build and Deploy to Windows VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.date.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate tag
        id: date
        shell: powershell
        run: |
          echo "tag=$([int]((Get-Date).ToUniversalTime() - [datetime]'1970-01-01').TotalSeconds)" >> $env:GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.date.outputs.tag }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend/EduPortalAPI
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.date.outputs.tag }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to app directory
        shell: powershell
        run: |
          New-Item -Path C:\app -ItemType Directory -Force
          Copy-Item -Path .\docker-compose.yml -Destination C:\app\ -Force
          Copy-Item -Path .\database -Destination C:\app\ -Recurse -Force

      - name: Deploy with Docker Compose
        shell: powershell
        run: |
          Set-Location C:\app
          $env:TAG="${{ needs.build-and-push.outputs.tag }}"
          docker-compose pull
          docker-compose up -d
          docker system prune -f